# NumPy (Часть 1)

## Numpy

**NumPy** представляет собой библиотеку типов и функций для работы с массивами и матрицами, и является мультимодульным пакетом. 

Наиболее популярные модули: 

*random (случайный)*, 

*linalg (линейная алгебра)*, 

*fft (Fast Fourier Transform – быстрое преобразование Фурье)*, 

*polynomial (работа с полиномами)* 

и многие другие. 


_______________________________________________________________________________

Вначале модуль **NumPy** следует загрузить. При этом для него можно создать более короткое имя.

*import numpy as np*

После этого к любому объекту модуля можно обращаться, используя это короткое имя.

In [1]:
import numpy as np    # подключение NumPy

print(np.__version__) # версия NumPy

np.show_config()      # конфигурация NumPy

1.16.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


## Массивы


Основным объектом **NumPy** является массив элементов (в **NumPy** называется **numpy.ndarray**), как правило, чисел. 

Наиболее важные атрибуты объектов **ndarray**:

**ndarray.ndim** - число измерений (чаще их называют "оси") массива.

**ndarray.shape** - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.

**ndarray.size** - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.

**ndarray.dtype** - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. 
**NumPy** предоставляет большое количество вариантов, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.

**ndarray.itemsize** - размер каждого элемента массива в байтах.

**ndarray.data** - буфер, содержащий фактические элементы массива. Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.


Существует несколько способов создать массив. Один из них состоит в создании массива из списка с помощью функции array().



In [0]:
x = [2, 3, 4, 6] # создание списка
y = np.array(x)  # создание массива средствами NumPy
z = np.array(x, float) # создание массива средствами NumPy

In [3]:
print(type(x), x)
print(type(y), y)
print(type(z), z)

<class 'list'> [2, 3, 4, 6]
<class 'numpy.ndarray'> [2 3 4 6]
<class 'numpy.ndarray'> [2. 3. 4. 6.]


In [4]:
x.dtype

AttributeError: ignored

In [5]:
y.dtype

dtype('int64')

In [6]:
z.dtype

dtype('float64')

## Массивы могут быть и многомерными 

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6]], float) # пример двумерного массива (матрица)
b = np.array([[6, 5, 4], [3, 2, 1]])
c = np.array([[1, 2], [3, 4], [5, 6]])
matrix = [[1, 2, 4], [3, 6, 0]]
d = np.array(matrix, float)

In [9]:
print(a[1,2])
print(b[0,0])
print(c[2,1])
print(matrix[1][1])
print(d[1,1])

6.0
6
6
6
6.0


## Методы

Метод **shape** возвращает количество строк и столбцов в матрице

Метод **len** возвращает длину первого измерения (оси)

Метод **in** используется для проверки на наличие элемента в массиве

Метод **dtype** возвращает тип переменных, хранящихся в массиве

In [10]:
print('-----------shape-----------') 
print('a shape: ', a.shape)
print('d shape: ', d.shape)
print('-----------len-----------') 
print('a len: ', len(a))
print('b len: ', len(b))
print('c len: ', len(c))
print('-----------in-----------') 
print('2 in x: ', 2 in x)
print('2 in y: ', 2 in y)
print('78 in z: ', 78 in z)

-----------shape-----------
a shape:  (2, 3)
d shape:  (2, 3)
-----------len-----------
a len:  2
b len:  2
c len:  3
-----------in-----------
2 in x:  True
2 in y:  True
78 in z:  False


### Reshape

Массивы можно переформировать при помощи метода, который задает новый многомерный массив.  Метод **reshape** создает новый массив, а не модифицирует оригинальный.



In [11]:
mass = np.array(range(10), float)
print('mass v01: ', mass)
print('mass v01 shape: ', mass.shape)
mass = mass.reshape((5, 2))
print('mass v02: ', mass)
print('mass v02 shape: ', mass.shape)


mass v01:  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
mass v01 shape:  (10,)
mass v02:  [[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
mass v02 shape:  (5, 2)


### Copy

Метод **copy** используется для создания копии существующего массива в памяти. Связывание имен в python работает и с массивами.

In [12]:
a = np.array([1, 2, 3], float)
b = a
c =  a.copy()
a[0] = 0
print(a)
print(b)
print(c)

[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]


### Fill

Метод **fill** - заполнение массива одинаковым значением

In [13]:
a = np.array([1, 2, 3], float)
print(a)
a.fill(0)
print(a)

[1. 2. 3.]
[0. 0. 0.]


###  Transpose
Транспонирование массивов также возможно, при этом создается новый массив

In [14]:
a = np.array(range(6), float).reshape((2, 3))
print(a)
print(a.transpose())

[[0. 1. 2.]
 [3. 4. 5.]]
[[0. 3.]
 [1. 4.]
 [2. 5.]]


### Flatten

Многомерный массив можно переконвертировать в одномерный при помощи метода **flatten**

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
print(a.flatten())

[[1. 2. 3.]
 [4. 5. 6.]]
[1. 2. 3. 4. 5. 6.]


### Concatenate

Два или больше массивов можно сконкатенировать при помощи метода **concatenate**

In [16]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
print(np.concatenate((a, b, c)))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


Если массив не одномерный, можно задать ось, по которой будет происходить соединение. По умолчанию (не задавая значения оси), соединение будет происходить по первому измерению:


In [17]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
print(np.concatenate((a,b)))
print(np.concatenate((a,b), axis=0))
print(np.concatenate((a,b), axis=1))

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


## Hstack и Vstack

Несколько массивов могут быть объединены вместе вдоль разных осей с помощью функций hstack и vstack. hstack() объединяет массивы по первым осям, vstack() — по последним

In [18]:
a = np.array([[1, 2], [3, 4]])
print(a)
b = np.array([[5, 6], [7, 8]])
print(b)
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## Column_stack и row_stack

Функция column_stack() объединяет одномерные массивы в качестве столбцов двумерного массива. Аналогично для строк имеется функция row_stack()

In [19]:
print(np.column_stack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


In [20]:
print(np.row_stack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Hsplit

Разбиение массива
Используя hsplit() вы можете разбить массив вдоль горизонтальной оси, указав либо число возвращаемых массивов одинаковой формы, либо номера столбцов, после которых массив разрезается "ножницами":


In [21]:
a = np.arange(12).reshape((2, 6))
print(a)
print(np.hsplit(a, 3))  # Разбить на 3 части
print(np.hsplit(a, (3, 4)))  # Разрезать a после третьего и четвёртого столбца

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
[array([[0, 1, 2],
       [6, 7, 8]]), array([[3],
       [9]]), array([[ 4,  5],
       [10, 11]])]


## Shuffle

Перемешать NumPy массив можно с помощью функции shuffle

In [23]:
import random as rand
a = np.arange(10)
print(a)
rand.shuffle(a)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[2 4 3 5 8 0 9 7 6 1]


### Метод newaxis

В заключении, размерность массива может быть увеличена при использовании константы newaxis в квадратных скобках


In [24]:
a = np.array([1, 2, 3], float)
print(a)
print(a[:,np.newaxis])
print(a[:,np.newaxis].shape)

print(b[np.newaxis,:])
print(b[np.newaxis,:].shape)

[1. 2. 3.]
[[1.]
 [2.]
 [3.]]
(3, 1)
[[[5 6]
  [7 8]]]
(1, 2, 2)


## [Модуль NumPy.random](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html)

Модуль random используется генерации псевдослучайных чисел. Числа являются псевдо случайными, в том плане что, они сгенерированы детерминистически из порождающего элемента (**seed number**), но рассредоточены в статистическом сходстве с случайным образом. Для генерации NumPy использует особенный алгоритм который имеет название Mersenne Twister.



In [25]:
print(np.random)

import numpy.random as rand  # можно присвоить отдельное имя
print(rand)

<module 'numpy.random' from '/usr/local/lib/python3.6/dist-packages/numpy/random/__init__.py'>
<module 'numpy.random' from '/usr/local/lib/python3.6/dist-packages/numpy/random/__init__.py'>


In [26]:
rand.seed(5) # задаем пораждающий элемент
print(rand.randn(4))
rand.seed(5) # задаем пораждающий элемент
print(rand.randn(4))
rand.seed(3) # задаем пораждающий элемент
print(rand.randn(4))

[ 0.44122749 -0.33087015  2.43077119 -0.25209213]
[ 0.44122749 -0.33087015  2.43077119 -0.25209213]
[ 1.78862847  0.43650985  0.09649747 -1.8634927 ]


**Seed** это целое число. Каждая программа которая запускается с одинаковым seed будет генерировать одинаковую последовательность чисел каждый раз. Это может быть полезно для отладки. Если эта команда не будет выполнена, то NumPy автоматически выбирает случайный seed (базирующийся на времени), который является разным при каждом запуске программы.

In [27]:
print(rand.randn(4, 5))

[[-0.2773882  -0.35475898 -0.08274148 -0.62700068 -0.04381817]
 [-0.47721803 -1.31386475  0.88462238  0.88131804  1.70957306]
 [ 0.05003364 -0.40467741 -0.54535995 -1.54647732  0.98236743]
 [-1.10106763 -1.18504653 -0.2056499   1.48614836  0.23671627]]


In [28]:
rand.rand(6).reshape((2,3)) 

array([[0.30636353, 0.22195788, 0.38797126],
       [0.93638365, 0.97599542, 0.67238368]])

# Создание массивов (2)

## Arange

Функция **arange** аналогична по своему назначению функции **range** из стандартной библиотеки Python. Ее основное отличие заключается в том, что **arange** позволяет строить вектор с указанием шага в виде десятичной дроби.

Синтаксис использования функции следующий:

arange(stop)

arange(start, stop)

arange(start, stop, step)

In [29]:
a = np.arange(5, dtype=float)
print(a)
b = np.arange(1, 6, 2, dtype=int)
print(b)

[0. 1. 2. 3. 4.]
[1 3 5]


# Задание 1: 

Опишите результат работы следующей ячейки (создайте новую ячейку типа Markdown и опишите в ней результат)

In [30]:
print(np.arange(0, 8, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]


Здесь создается новый одномерный ndarray, заполняемый числами от 0 до 8 с шагом 0.1.


## Zeros и Ones

Функции zeros и ones создают новые массивы с установленной размерностью, заполненные этими значениями. Это, наверное, самые простые в использовании функции для создания массивов

In [31]:
print(np.ones((2,3), dtype=float))
print(np.zeros(7, dtype=int))

[[1. 1. 1.]
 [1. 1. 1.]]
[0 0 0 0 0 0 0]


## Zeros_like и Ones_like

Функции zeros_like и ones_like могут преобразовать уже созданный массив, заполнив его нулями и единицами соответственно

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
print(np.zeros_like(a))
print(np.ones_like(a))

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


## Identity

Для создания квадратной матрицы с главной диагональю, которая заполненная единицами, воспользуемся методом identity

In [33]:
print(np.identity(4, dtype=float))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Eye
Функция eye возвращает матрицу с единичками на к-атой диагонали

In [34]:
print(np.eye(4, k=1, dtype=float))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


## Базовые операции


In [38]:
print (y)
print(type(y))
print(y[y>3])

[2 3 4 6]
<class 'numpy.ndarray'>
[4 6]


In [39]:
print (x)
print(type(x))
print(x * 5)

[2, 3, 4, 6]
<class 'list'>
[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [37]:
print (y)
print(y * 5)

[2 3 4 6]
[10 15 20 30]


In [40]:
print (x)
print(x ** 2)

[2, 3, 4, 6]


TypeError: ignored

In [41]:
print (y)
print(y ** 2)

[2 3 4 6]
[ 4  9 16 36]


Математические операции над массивами выполняются поэлементно. 

Создается новый массив, который заполняется результатами действия оператора.

## Вывод 

Одномерные массивы осуществляют операции индексирования, срезов и итераций схожим образом с обычными списками и другими последовательностями Python (удалять с помощью срезов нельзя).

In [42]:
print(x)
print(x[1:3])

[2, 3, 4, 6]
[3, 4]


In [43]:
print(y)
print(y[1:3])

[2 3 4 6]
[3 4]


In [44]:
print(x)
print(x[[0, 2]])

[2, 3, 4, 6]


TypeError: ignored

In [45]:
print(y)
print(y[[0, 2]])

[2 3 4 6]
[2 4]


## Задания

1) Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B


2) Создайте массив из 1000 элементов со случайными значениями в диапазоне от [1, 10000]. Вывести n наибольших значений в массиве


3) Создайте матрицу (90х76) со случайными значениями в диапазоне от [1, 10000]. Посчитайте ранг матрицы.


In [68]:
"""Задание 1"""

a = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3],[3,2,1],[4,5,6],[7,8,9],[2,2,3]])
b = np.array([[1,2],[3,1]])
c = set(b.flatten())
for i in range (0,len(a)):
  if len(set(a[i]) ^ c) == 0:
    print("Row",i + 1,":",a[i])

Row 1 : [1 2 3]
Row 4 : [1 2 3]
Row 5 : [3 2 1]


In [69]:
"""Задание 2"""

r = rand.randint(0, 10000, 1000)
n = int(input("Введите n >> "))
r.sort()
print(r[-n:])

Введите n >> 10
[9856 9884 9893 9903 9910 9976 9981 9985 9991 9992]


In [73]:
"""Задание 3"""

matrix = rand.randint(0, 10000, 90*76).reshape((90,76))
matrix.shape
print(np.linalg.matrix_rank(matrix))

76


# [Модуль linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)


### Возведение в степень
linalg.matrix_power(M, n) - возводит матрицу в степень n.

### Разложения
linalg.cholesky(a) - разложение Холецкого.

linalg.qr(a[, mode]) - QR разложение.

linalg.svd(a[, full_matrices, compute_uv]) - сингулярное разложение.


linalg.eig(a) - собственные значения и собственные векторы.

linalg.norm(x[, ord, axis]) - норма вектора или оператора.

linalg.cond(x[, p]) - число обусловленности.

linalg.det(a) - определитель.

linalg.slogdet(a) - знак и логарифм определителя (для избежания переполнения, если сам определитель очень маленький).

### Системы уравнений
linalg.solve(a, b) - решает систему линейных уравнений Ax = b.

linalg.tensorsolve(a, b[, axes]) - решает тензорную систему линейных уравнений Ax = b.

linalg.lstsq(a, b[, rcond]) - метод наименьших квадратов.

linalg.inv(a) - обратная матрица.

## Задания

Используя модуль linalg выполните расчеты над автоматически генерируемой вектором/матрицей:

1) Решите систему линейных уравнений Ax = b

2) Посчитать определитель матрицы

3) Определить норму вектора

4) Возведите матрицу в степень n

5) Выведите обратную матрицу

In [0]:
import numpy.linalg as alg

In [76]:
a = rand.randint(0, 100, 25).reshape((5,5))
b = rand.randint(0, 100, 5).reshape((5,1))
print(a)
print(b)

[[52 11 34 80 38]
 [77 45 76 81 49]
 [98 63 75 95 31]
 [97  1 62 97 99]
 [ 3 37 54 96 75]]
[[36]
 [ 4]
 [77]
 [56]
 [26]]


In [77]:
print(alg.solve(a,b))  # Task 1

[[ 1.70982169]
 [ 3.87788481]
 [-5.49695689]
 [ 0.09742802]
 [ 2.19828506]]


In [78]:
print(alg.det(a))  # Task 2

217998036.0000004


In [80]:
print(alg.norm(b))  # Task 3

105.13324878457813


In [83]:
n = int(input("Enter n>> "))
print(alg.matrix_power(a, n))  # Task 4

Enter n>> 1
[[52 11 34 80 38]
 [77 45 76 81 49]
 [98 63 75 95 31]
 [97  1 62 97 99]
 [ 3 37 54 96 75]]


In [84]:
print(alg.inv(a))  # Task 5

[[-1.16871053e-02 -2.24119588e-02  2.11218875e-02  1.31986740e-02
  -5.58868338e-03]
 [-4.87537420e-02 -6.25168201e-02  5.74801876e-02  1.70955302e-02
   1.92216411e-02]
 [ 3.21775651e-02  9.78747487e-02 -6.56765825e-02 -2.80952118e-02
  -1.60161351e-02]
 [ 3.18439750e-02 -9.02301707e-05 -5.89478705e-03 -1.10740906e-02
   9.78981297e-04]
 [-3.94088046e-02 -3.86162149e-02  2.56306988e-02  2.54416466e-02
   1.43527256e-02]]
